language: java
script:
- mvn package
deploy:
  provider: heroku
  api_key:
    secure: K7qWeCk5bKzH0Jf4F8Ic0dMSZXLB0WXNEdWbmI10aeD0lxJRndJ71FZWC6bdkCfCa8q45a3klzf4ESsU5GGPeTqfkbwaVZT+FInoPDt89KBZgJ2XhuVr0mlcT9J/6VpKTLzRN3m5g/09dDLmF1T/AVaE27VpENnIOfRA2KR3NrZ5kUif3FX2EtGx7HuetB651Zcjg2SFtyl48MG5gX/MbxECIwUMWM7w65NqnD6E04nQmwEf6L4JqQzH0u3UL1b0mWstGMMo1JYTQW6gv2asnmIa48oAwQLK4v7i0pU8eInjMXs0LwPsOpB7L4+apV6HENR5JjrC4LOwoVlkikkpbD7fRgeDyIqPCzZSQEb56dktJR1TnqJ69B0KKzIxd6m6WhTGUyWDygWLQ1VcRhgJyzv+sx0sYwy7NKj9dMCZVzlCgvYmIIfHTi6PFNDHUn+MZvtSwp1xBQz5+vp7ACBLG0aHlp7Wl4ryIDUbHNSlQ2PPMCp+C/WMvl1SxQ6QGcZxXcqBKt5C0Dnj4a4Kk979xMmZPgS7oTDjKCShN5YOs44nPBi9lV2W6ETZaMQeaeTIQz+NWyd8/IW1uYgJYH3foO6UiKhxkF3w7lhbNzkt00tTuGtiTIoBV13gYRdjTVxXo8345ez/BXhzr9qsM3QnRHejcBd1RZHGN2I0GSTIdOw=
  app:
    master: material-contacts-trault14
    staging: material-contacts-tim-staging
